import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import UserProvider from "@/providers/user_provider";
import FetchProvider from "@/providers/fetch_provider";
import { SocketProvider } from "@/providers/socket_provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <FetchProvider>
          <UserProvider>
            <SocketProvider>
              {children}
            </SocketProvider>
          </UserProvider>
        </FetchProvider>
      </body>
    </html>
  );
}
